# Generated by Django 6.0.5 on 2026-05-22 18:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='product',
            old_name='primary_image_url',
            new_name='image',
        ),
        migrations.AlterField(
            model_name='product',
            name='image',
            field=models.URLField(blank=True, max_length=500, null=True),
        ),
        migrations.AddField(
            model_name='product',
            name='imagekit_file_id',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.RenameField(
            model_name='productimage',
            old_name='image_url',
            new_name='image',
        ),
        migrations.AlterField(
            model_name='productimage',
            name='image',
            field=models.URLField(blank=True, max_length=500, null=True),
        ),
        migrations.AddField(
            model_name='productimage',
            name='imagekit_file_id',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.RemoveField(
            model_name='productimage',
            name='image_file',
        ),
    ]
