# Generated by Django 6.0.5 on 2026-05-18 22:04

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='HeroSlide',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=100)),
                ('highlight', models.CharField(blank=True, max_length=100)),
                ('subtitle', models.CharField(max_length=255)),
                ('cta', models.CharField(max_length=50)),
                ('link', models.CharField(max_length=100)),
                ('image_url', models.URLField(blank=True, max_length=500)),
                ('image_file', models.ImageField(blank=True, null=True, upload_to='store/')),
                ('accent_color', models.CharField(default='#E8879A', max_length=20)),
                ('order', models.IntegerField(default=0)),
            ],
            options={
                'ordering': ['order'],
            },
        ),
        migrations.CreateModel(
            name='StoreSettings',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(default='ShikharShoes', max_length=255)),
                ('address', models.TextField(blank=True)),
                ('email', models.EmailField(blank=True, max_length=254)),
                ('phone', models.CharField(blank=True, max_length=20)),
                ('hours_weekday', models.CharField(default='10:00 AM - 8:00 PM', max_length=100)),
                ('hours_saturday', models.CharField(default='10:00 AM - 9:00 PM', max_length=100)),
                ('hours_sunday', models.CharField(default='11:00 AM - 7:00 PM', max_length=100)),
                ('map_embed_url', models.TextField(blank=True)),
                ('latitude', models.DecimalField(blank=True, decimal_places=6, max_digits=10, null=True)),
                ('longitude', models.DecimalField(blank=True, decimal_places=6, max_digits=10, null=True)),
                ('instagram_url', models.URLField(blank=True)),
                ('facebook_url', models.URLField(blank=True)),
                ('twitter_url', models.URLField(blank=True)),
            ],
        ),
    ]
